name: Twitter Scraper

on:
  repository_dispatch:
    types: [start-scrape]

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run in Docker container
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/puppeteer/puppeteer:20.9.0
          options: --shm-size=2gb -v ${{ github.workspace }}:/app
          run: |
            cd /app
            
            # Install dependencies if node_modules doesn't exist
            if [ ! -d "node_modules" ]; then
              echo "Installing dependencies..."
              npm ci
              echo "Dependencies installed successfully"
            else
              echo "Using existing node_modules"
            fi
            
            # Verify Chrome is available
            echo "Checking Chrome installation..."
            which chromium
            chromium --version
            echo "Chrome verification complete"
            
            # Run the scraper
            NODE_OPTIONS="--max-old-space-size=4096" PUPPETEER_EXECUTABLE_PATH="/usr/bin/chromium" node router.js --payload '${{ toJson(github.event.client_payload) }}'
